config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts #,except: [:edit], only: [:edit]
  resources :kinds

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts

  validates :description, presence: true
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true, html: {class: "basic-grey"}) do |form| %>
  <h1><%= kind.model_name.human(count: 1) %></h1>

  <script>
      $.notify("<%= if kind.errors.any?
                kind.errors.full_messages.each do |message|
                message
                end end %>")
  </script>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit t('buttons.save'), class: "btn btn-primary" %>
    <%= link_to t('buttons.back'), kinds_path, class: "btn btn-success" %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/index.html.erb
<div class="basic-grey">
  <script>
      $.notify('<%= notice %>', 'success')
  </script>

  <h1><%= t('activerecord.models.kind.other')%></h1>

  <table>
    <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to t('buttons.show'), kind %></td>
        <td><%= link_to t('buttons.edit'), edit_kind_path(kind) %></td>
        <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: {confirm: t('messages.confirm')} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to t('buttons.new'), new_kind_path, class: 'btn btn-primary' %>
  <%= link_to t('buttons.back'), root_path, class: "btn btn-success" %>
</div>

app/views/kinds/new.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>