config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts #,except: [:edit], only: [:edit]
  resources :kinds

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  has_one :address
  has_many :phones

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: :true

  validates :name, presence: true, length: {minimum: 2}
  validates :email, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_kinds, only: [:new, :edit, :update, :create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html {redirect_to contacts_path, notice: I18n.t('messages.created')}
        format.json {render :show, status: :created, location: @contact}
      else
        format.html {render :new}
        format.json {render json: @contact.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html {redirect_to contacts_path, notice: I18n.t('messages.updated')}
        format.json {render :show, status: :ok, location: @contact}
      else
        format.html {render :edit}
        format.json {render json: @contact.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html {redirect_to contacts_url, notice: I18n.t('messages.destroyed')}
      format.json {head :no_content}
    end
  end

  private

  def set_kinds
    @kinds = Kind.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :email, :kind_id, :rmk,
                                    address_attributes: [:city, :street, :state, :id],
                                    phones_attributes: [:id, :phone, :_destroy])
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true, html: {class: "basic-grey"}) do |form| %>
  <h1><%= contact.model_name.human(count: 1) %></h1>

  <% if contact.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%#= collection_select(:contact, :kind_id, @kinds, :id, :description) %>
    <%= form.collection_select(:kind_id, @kinds, :id, :description) %>
  </div>

  <%= form.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %>
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= address_fields.label :city %>
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= address_fields.label :state %>
      <%= address_fields.select(:state, options_for_states(@contact.address.state)) %>
    </div>
  <% end %>

  <div id="phones">
    <%= form.fields_for :phones do |phones_fields| %>
      <%= render partial: 'phone_fields', locals: {f: phones_fields} %>
    <% end %>
    <div class="field">
      <%= form.label ' ' %>
      <%= link_to_add_association([t('buttons.add')], form, :phones) %>
    </div>
  </div>

  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit t('buttons.save'), class: "btn btn-primary" %>
    <%= link_to t('buttons.back'), contacts_path, class: "btn btn-success" %>
  </div>

<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'phone-field' %>
    <%= link_to_remove_association(t('buttons.destroy'), f) %>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<div class="basic-grey">
  <script>
    $.notify('<%= notice %>', 'success')
  </script>

  <h1><%= "#{t('messages.list')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>

  <table>
    <thead>
    <tr>
      <th><%= @contacts.model.human_attribute_name("name") %></th>
      <th><%= @contacts.model.human_attribute_name("kind") %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @contacts.each do |contact| %>
      <tr style="background-color: <%= cycle('white', '' ) %>">
        <td><%= contact.name %></td>
        <td><%= contact.kind.description %></td>
        <td><%= link_to t('buttons.show'), contact %></td>
        <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
        <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: {conffirm: t('messages.confirm')} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
  <%= paginate @contacts %>
  <br>

  <%= link_to t("buttons.new"), new_contact_path, class: 'btn btn-primary' %>
  <%= link_to t("buttons.back"), root_path, class: 'btn btn-success' %>
</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>