config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts #,except: [:edit], only: [:edit]
  resources :kinds

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_adress, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @adresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @adress = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @adress = Address.new(adress_params)

    respond_to do |format|
      if @adress.save
        format.html { redirect_to @adress, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @adress }
      else
        format.html { render :new }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @adress.update(adress_params)
        format.html { redirect_to @adress, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @adress }
      else
        format.html { render :edit }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @adress.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adress_params
      params.require(:adress).permit(:street, :city, :state, :contact_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: adress, local: true, html: {class: "basic-grey"}) do |form| %>
  <h1>Adress</h1>
  <% if adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
      <% adress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :contact_id %>
    <%= form.text_field :contact_id %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "button" %>
    <%= link_to 'Back', addresses_path, class: "button" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<%= render 'form', adress: @adress %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adresses.each do |adress| %>
      <tr>
        <td><%= adress.street %></td>
        <td><%= adress.city %></td>
        <td><%= adress.state %></td>
        <td><%= adress.contact %></td>
        <td><%= link_to 'Show', adress %></td>
        <td><%= link_to 'Edit', edit_address_path(adress) %></td>
        <td><%= link_to 'Destroy', adress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<%= render 'form', adress: @adress %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @adress.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @adress.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @adress.state %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @adress.contact %>
</p>

<%= link_to 'Edit', edit_address_path(@adress) %> |
<%= link_to 'Back', addresses_path %>